deployment:
  tasks:
    - current_branch=$(git rev-parse --abbrev-ref HEAD)
    # - if [ $current_branch == "main" ]; then export DEPLOYPATH=/home/akbulute/development/; fi;
    - if [ $current_branch == "main" ]; then export DEPLOYPATH=/home/akbulute/public_html/; fi;
    - composer install --no-dev --optimize-autoloader
    - /home/akbulute/nodevenv/public_html/public/24/bin/npm --prefix /home/akbulute/repositories/akbulut install
    - /home/akbulute/nodevenv/public_html/public/24/bin/npm --prefix /home/akbulute/repositories/akbulut run build
    - /bin/cp -R * $DEPLOYPATH